# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
# Dependencies
install:
    - go get github.com/robotology/yarp
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make 
