# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
# Dependencies
before_script: 
  - sudo sh -c 'echo "deb http://www.icub.org/ubuntu trusty contrib/science" > /etc/apt/sources.list.d/icub.list'
  - sudo apt-get update
  - sudo apt-get install yarp
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make 
